# FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04
FROM ghcr.io/opennmt/ctranslate2:latest-ubuntu20.04-cuda11.2

WORKDIR /app

COPY requirements.txt README.md LICENCE ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:9000", "--workers", "1", "--timeout", "0", "app.webservice:app", "-k", "uvicorn.workers.UvicornWorker"]
